import java.awt.Color;
import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import java.awt.event.*;
public class parentdetails extends array {
    JFrame jf3;
    parentdetails(){
        JFrame jf3 = new JFrame();
        jf3.setSize(2000, 800);
        jf3.setVisible(true);
        jf3.setLayout(null);
        JLabel jld =new JLabel();
        jf3.add(jld);
                jld.setText("Your Third Step 'Parent Details'");
        jld.setBounds(500, 0, 500, 100);
        jld.setForeground(Color.BLUE);
        jld.setFont(new FontUIResource("Italic", 50, 30));
        JLabel fad =new JLabel(" Your Father Aadhar no.:-");
        jf3.add(fad);
        fad.setBounds(100, 250, 300, 40);
        fad.setFont(new FontUIResource("Italic", 50, 20));
        JTextField fadt =new JTextField();
        jf3.add(fadt);
        fadt.setBounds(380, 250, 150, 40);
        JLabel mad =new JLabel("Your Mother Aadhar no.:-");
        jf3.add(mad);
        mad.setBounds(100, 200, 300, 40);
        mad.setFont(new FontUIResource("Italic", 50, 20));
        JTextField madt =new JTextField();
        jf3.add(madt);
        madt.setBounds(380, 200, 150, 40);
        JLabel fo =new JLabel(" Father Name:-");
        jf3.add(fo);
        fo.setBounds(100, 320, 200, 40);
        fo.setFont(new FontUIResource("Italic", 50, 20));
        JTextField tffn =new JTextField();
        jf3.add(tffn);
        tffn.setBounds(320, 320, 150, 40); 
        JLabel fnl =new JLabel("First Name");
        jf3.add(fnl);
        fnl.setBounds(320, 280, 150, 40);
        JTextField fsn =new JTextField();
        jf3.add(fsn);
        fsn.setBounds(500, 320, 150, 40); 
        JLabel fsnl =new JLabel("Second Name");
        jf3.add(fsnl);
        fsnl.setBounds(500, 280, 150, 40);
        JLabel mn1 =new JLabel(" Mother Name:-");
        jf3.add(mn1);
        mn1.setBounds(100, 400, 200, 40);
        mn1.setFont(new FontUIResource("Italic", 50, 20));
        JTextField tfmn =new JTextField();
        jf3.add(tfmn);
        tfmn.setBounds(320, 400, 150, 40); 
        JLabel mnl =new JLabel("First Name");
        jf3.add(mnl);
        mnl.setBounds(320, 360, 150, 40);
        JTextField msn =new JTextField();
        jf3.add(msn);
        msn.setBounds(500, 400, 150, 40); 
        JLabel msnl =new JLabel("Second Name");
        jf3.add(msnl);
       msnl.setBounds(500, 360, 150, 40); 
        JButton nd3 =new JButton("SUBMIT");
        jf3.add(nd3);
        nd3.setBounds(500, 500, 80, 30); 
        nd3.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                a[10][1]=fad.getText();
                a[10][2]=fadt.getText();
a[11][1]=mad.getText();
a[11][2]=madt.getText();
a[12][1]=fo.getText();
String x=tffn.getText();
String y=fsn.getText();
a[12][2]=x+y;
a[13][1]=mn1.getText();
x=tfmn.getText();
y=msn.getText();
 a[13][2]=x+y;
          new addressdetails();
                jf3.dispose(); 
            }});
   }
}
